100
(0.5, 312471852.0, 0.29, 6.0, (7, 14), 'fitted-scaled', 'econ-scaled', 'oct21-scaled', 0.1, 0.05, 2, 'dynamic_gradient')
Traceback (most recent call last):
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 846, in <module>
    main()
  File "run_linearization_heuristic.py", line 121, in main
    run_lin_heur_and_save_yaml(delta, xi, icus, mtests, atests, n_days, region, test_freq, lockdown_freq, econ, init, eta, groups, start_day, trust_region_radius, max_inner_iterations_mult, initial_uhat, optimize_bouncing, scaling, money_scaling)
  File "run_linearization_heuristic.py", line 160, in run_lin_heur_and_save_yaml
    dynModel = run_linearization_heuristic(simulation_params, experiment_params, start_day, trust_region_radius, max_inner_iterations_mult, initial_uhat, optimize_bouncing)
  File "run_linearization_heuristic.py", line 250, in run_linearization_heuristic
    universe_params = yaml.load(file, Loader=yaml.FullLoader)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/parser.py", line 406, in parse_indentless_sequence_entry
    KeyToken, ValueToken, BlockEndToken):
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/scanner.py", line 255, in fetch_more_tokens
    return self.fetch_plain()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/scanner.py", line 679, in fetch_plain
    self.tokens.append(self.scan_plain())
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/scanner.py", line 1290, in scan_plain
    ch = self.peek(length)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 91, in peek
    self.update(index+1)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "parameters/fitted-scaled.yaml", position 24576
srun: error: sh02-01n27: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=15367700.0
