srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 5 nodes, setting nnodes to 1
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
srun: error: sh03-01n31: task 0: Exited with exit code 1
srun: error: sh03-01n31: task 0: Exited with exit code 1
srun: error: sh03-01n31: task 0: Exited with exit code 1
srun: error: sh03-01n31: task 0: Exited with exit code 1
srun: Terminating job step 9428932.7
srun: Terminating job step 9428932.3
srun: Terminating job step 9428932.5
srun: Terminating job step 9428932.6
srun: error: sh03-01n31: task 0: Exited with exit code 1
srun: Terminating job step 9428932.4
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: Terminating job step 9428932.12
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: Terminating job step 9428932.9
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: error: sh03-01n32: task 0: Exited with exit code 1
srun: Terminating job step 9428932.10
srun: Terminating job step 9428932.11
srun: Terminating job step 9428932.13
srun: Terminating job step 9428932.8
2160
2160
2160
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
2160
srun: error: sh03-01n29: task 0: Exited with exit code 1
srun: Terminating job step 9428932.0
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
  File "run_linearization_heuristic.py", line 871, in <module>
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
    main()
    main()
  File "run_linearization_heuristic.py", line 99, in main
  File "run_linearization_heuristic.py", line 99, in main
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
    delta = all_instances[instance_index][0]
    delta = all_instances[instance_index][0]
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
Traceback (most recent call last):
    main()
  File "run_linearization_heuristic.py", line 99, in main
  File "run_linearization_heuristic.py", line 871, in <module>
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
    main()
    delta = all_instances[instance_index][0]
IndexError: list index out of range
  File "run_linearization_heuristic.py", line 99, in main
IndexError: list index out of range
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
Traceback (most recent call last):
IndexError: list index out of range
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
srun: error: sh03-01n29: task 0: Exited with exit code 1
srun: error: sh03-01n29: task 0: Exited with exit code 1
srun: Terminating job step 9428932.2
srun: Terminating job step 9428932.1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: Terminating job step 9428932.22
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: Terminating job step 9428932.25
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: Terminating job step 9428932.24
srun: Terminating job step 9428932.26
srun: Terminating job step 9428932.23
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: error: sh03-01n33: task 0: Exited with exit code 1
srun: Terminating job step 9428932.20
srun: Terminating job step 9428932.18
srun: Terminating job step 9428932.15
srun: Terminating job step 9428932.21
srun: Terminating job step 9428932.17
srun: Terminating job step 9428932.19
srun: Terminating job step 9428932.14
srun: Terminating job step 9428932.16
2160
2160
2160
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linearization_heuristic.py", line 871, in <module>
    main()
  File "run_linearization_heuristic.py", line 99, in main
    delta = all_instances[instance_index][0]
IndexError: list index out of range
srun: error: sh03-01n34: task 0: Exited with exit code 1
srun: Terminating job step 9428932.29
srun: error: sh03-01n34: task 0: Exited with exit code 1
srun: error: sh03-01n34: task 0: Exited with exit code 1
srun: Terminating job step 9428932.28
srun: Terminating job step 9428932.27
